import React, { Component } from "react";

class Rules extends Component {
  render() {
    return (
      <div>
        <div className="header-1 centered-title">Crypto Against Humanity Player's Guide</div>
        <div className="lbl-text margin-text">Crypto Against Humanity is a platform for content creation of card combinations.
         Crypto Against Humanity consists of two types of cards. White cards, which typically represent a noun or pronoun, and black
         cards, which usually are sentences or phrases with blank spaces. With Crypto Against Humanity, these cards and combinations 
         are completely generated by the community. As a user you can create a white card. Black cards are chosen randomly 
         every 2 hours based on a Token Curated Registry (TCR). The white cards can be bought and sold for ether for fixed amounts 
         which increase as more people buy in and decrease as people sell off. </div>
         <div className="header-1 centered-title"> Use Cases </div>
         <div className="lbl-text margin-text">Alice opens Crypto Against Humanity and notices the black card with the text
         "____, Don't Ask, Don't Tell." She </div>
      </div>
    );
  }
}

export default Rules;